version: '2'

services:
  genieacsserver:
    image: romanromanovv/genieacsdocker:prod1
    container_name: genieacs-cont
    ports:
      - "3000:3000"
      - "7547:7547"
      - "7557:7557"
      - "7567:7567"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo-cont
    volumes:
      - /opt/mongo-volume/:/data/db
